### ISSUE TITLE
Requirement is pinned for python-awair 0.1.1 - 0.2.0: aiohttp>=3.6.1,<3.7.0

### ISSUE THREAD

**Issue by MartinHjelmare** [ahayworth/python_awair#18]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Home Assistant currently depends on python-awair 0.1.1. When a new release is done where this is addressed it would be good to also bump the version used in Home Assistant. 

Thanks for your support of Home Assistant!

**Comment by ahayworth** [comment]
> To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

This is a great way to _ensure_ future issues, in my opinion. 🤣

aiohttp [follows semantic versioning](https://docs.aiohttp.org/en/stable/faq.html?highlight=semantic#what-is-the-api-stability-and-deprecation-policy), so we should be able to trust anything `< 4.0.0`.

@MartinHjelmare Do you see any problem with changing the requirements to `>= 3.6.1, < 4.0.0`? (Note to self: in `pyproject.toml` that would equate to a caret version - `^3.6.1`)

**Comment by MartinHjelmare** [comment]
Yes, `>= 3.6.1, < 4.0.0` is good. Thanks!
