### ISSUE TITLE
"Local sensors" support

### ISSUE THREAD

**Issue by nogweii** [ahayworth/python_awair#8]
Apparently Awair is starting to support reading the sensor data from the devices directly, via LAN, rather than only through their cloud. See [this document](https://docs.google.com/document/d/1001C-ro_ig7aEyz0GiWUiiJn0M6DLj47BYWj31acesg/edit?usp=sharing) (linked from the API documentation) for details.

It roughly looks like this, though not every attribute is returned for all devices:

```
GET http://192.168.1.1/air-data/latest


{"timestamp":"2020-06-30T23:30:19.577Z","score":95,"temp":26.04,"humid":46.4,"co2":487,"voc":88,"pm25":8,"lux":27.9,"spl_a":52.4}
```

It's currently in beta for consumer devices, and supported in their enterprise deployments. I'm not expecting it to be added to the library immediately, but wanted to capture the details.

**Comment by ahayworth** [comment]
Whoops, didn't mean to close this when I merged #9 🤦 

But - Thanks to @bpowers, we now have support for the local API (at least for consumer devices, enterprise support is largely unbuilt overall). See [release notes](https://github.com/ahayworth/python_awair/releases/tag/0.2.0) and [pypi package](https://pypi.org/project/python-awair/) !
